# Generated by Django 4.0.3 on 2022-03-12 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.AlterModelOptions(
            name='problems',
            options={'verbose_name': 'Проблема', 'verbose_name_plural': 'Проблемы'},
        ),
        migrations.CreateModel(
            name='Obrashenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('first_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('second_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('otchestvo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('vozrast', models.IntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('pol', models.IntegerField(choices=[(1, 'Мужской'), (2, 'Женский')], default=1, verbose_name='Пол')),
                ('adress', models.CharField(max_length=255, verbose_name='Место жительства')),
                ('opisanie', models.TextField(blank=True, null=True, verbose_name='Описание проблемы')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.status', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
            },
        ),
    ]
