# Generated by Django 4.0.3 on 2022-03-12 01:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_status_alter_problems_options_obrashenie'),
    ]

    operations = [
        migrations.AddField(
            model_name='obrashenie',
            name='data_vnesenia',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата внесения'),
            preserve_default=False,
        ),
    ]
