# Generated by Django 4.0.3 on 2022-03-12 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_obrashenie_data_vnesenia'),
    ]

    operations = [
        migrations.AddField(
            model_name='obrashenie',
            name='problems',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.problems', verbose_name='Проблемы'),
        ),
        migrations.AlterField(
            model_name='obrashenie',
            name='status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.status', verbose_name='Статус'),
        ),
    ]
